# Generated by Django 4.1.3 on 2022-12-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
    ]
