# Generated by Django 4.1.3 on 2022-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina', '0002_alter_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
