# Generated by Django 4.1.3 on 2022-12-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina', '0004_alter_books_authors_alter_books_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.TextField(),
        ),
    ]
